apiVersion: v1
kind: Pod
metadata:
  name: get-environments-testing
  namespace: environment-lister
spec:
  containers:
  - name: get-environments
    command: ["/usr/bin/python", "/apps/get_environments.py"]
    # command: ["sleep", "2000"]
    image: jgoodier/markdown2-kubectl:0.0.4
    imagePullPolicy: IfNotPresent
    env:
    - name: CLUSTER_NAME
      value: qa-gcp1
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
    volumeMounts:
    - mountPath: /apps
      name: config-volume
    - mountPath: /apps/docs
      name: docs
  restartPolicy: Never
  securityContext:
    fsGroup: 1001
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 1001
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: environment-lister-sa
  serviceAccountName: environment-lister-sa
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: get_environments.py
        path: get_environments.py
      name: get-environments
    name: config-volume
  - emptyDir: {}
    name: docs
